### ISSUE TITLE
Navnesøk

### ISSUE THREAD

**Issue by eriksjom** [statisticsnorway/mimir#1249]
**Beskrivelse**

ssb.nos brukere ønsker en tjeneste/applikasjon hvor de kan søke opp et navn og se hvor mange som heter det samme som seg. Vedlagt ligger en komprimert json-fil med de 300 mest populære navnene. Både fornavn, mellomnavn og etternavn. For at oppgaven skal være løst må følgende akseptansekriterier være oppfylt:

- Brukeren skal kunne søke på ett spesifikt navn og få opp hvor mange som heter det.
- Brukeren skal kunne søke på både et fornavn og et etternavn og både se hvor mange som heter hvert enkelt navn, men også kombinasjonen av de to
- Dersom det er 3 eller færre som har navnet (eller en kombinasjon av navnene) skal denne teksten dukke opp: "Det er 0-3 personer som heter [navn]"

**Brukerhistorie:**

Som en bruker av ssb.no
ønsker jeg å kunne søke opp mitt eget navn
slik at jeg kan se hvor mange som heter det samme som meg

**Resursser:**

Lenke til eksisterende navnesøk på ssb.no: https://www.ssb.no/befolkning/navn/statistikk/navn
Lenke til designsystem: https://statisticsnorway.github.io/design-system/#/
Lenke til designsystem-repo: https://github.com/statisticsnorway/ssb-component-library

**Vedlegg:**
Datagrunnlag [nameSearchPop300.zip](https://github.com/statisticsnorway/mimir/files/7167665/nameSearchPop300.zip)

**Comment by annesiri** [comment]
@ssb-cgn, vet du om dette er noe som kan lukkes?

**Comment by ssb-cgn** [comment]
Jeg lukker denne , det var en case oppgave i forbindelse med nyansettelse.
